name: STAGES
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  DEV_STAGE:
    runs-on: ubuntu-latest
    steps:
      - run: echo "DEV STAGR"
  PRD_STAGE:
    runs-on: ubuntu-latest
    environment: prd
    steps:
      - run: echo "PRD STAGE"
  
